repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-case-conflict

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.83.5
  hooks:
  - id: terraform_fmt
  - id: terraform_docs
  - id: terraform_tflint
  - id: terraform_checkov
  - id: terraform_tfsec
  - id: terraform_validate

- repo: https://github.com/zricethezav/gitleaks
  rev: v8.18.1
  hooks:
  - id: gitleaks

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.38.0
  hooks:
  - id: markdownlint
